name: 🌋M@TE🌋 Model Request
description: Request a model to be included in the hub
title: "M@TE Model Request: <name>"
labels: [new-model]

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to open a Model Request!"

  - type: input
    id: model-name
    attributes:
      label: Model Name
      description: "Suggest a name for your model"
      placeholder: "Expanding Earth"
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: "Please provide a short description of your model"
      placeholder: "It really is...expanding"
    validations:
      required: true

  - type: input
    id: for
    attributes:
      label: Field of research
      description: "Please submit a Field of Research (FOR) code. Please use [this resource]( https://vocabs.ardc.edu.au/viewById/316) to search codes."
      placeholder: "3706"
    validations:
      required: true
      
  - type: checkboxes
    id: type
    attributes:
      label: model type
      description: What type of model are you submitting?
      options:
        - published study
        - commmunity benchmark
        - attempted reproduction of a previous model (including with different codes, etc)
        - missing data model (input files available, requires re-running by community)
        - other
      default: 0
    validations:
      required: true

  - type: input
    id: model-publication
    attributes:
      label: Publication
      description: "Is there a link to a publication?"

  - type: input
    id: source-code
    attributes:
      label: Source Code
      description: "Is code for the model available? If so, please provide link to repository (GitHub, GitLab, BitBucket...)?"

  - type: input
    id: model-license
    attributes:
      label: License
      description: "If there is a license, please provide the name of the license (or None if there is no license specified)."
      placeholder: "CC-BY-4.0"
    validations:
      required: true
      
